=== jecisc/M1SGBD/TPXQuery2/foot_tp/clubs_scores.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xsi:schemaLocation="http://www.w3.org/2001/XMLSchema
                         http://www.w3.org/2001/XMLSchema.xsd"
            xmlns="http://caronc/schema/foot"
            targetNamespace="http://caronc/schema/foot"
            elementFormDefault="qualified">
  <!--les scores -->

<!-- le score après n journées -->
  <xs:complexType name="TypeScore">
    <xs:sequence>
      <xs:element name="nb_buts_marques" type="xs:nonNegativeInteger"/>
      <xs:element name="nb_buts_encaisses" type="xs:nonNegativeInteger"/>
      <xs:element name="nb_points" type="xs:nonNegativeInteger"/>
      <xs:element name="classement" type="xs:nonNegativeInteger"/>
    </xs:sequence>
    <xs:attribute name="nb_journees" type="xs:nonNegativeInteger" use="required"/>
  </xs:complexType>

  <!-- les clubs --> 
  <!-- Le type d'un club -->
  <xs:complexType name="TypeClub">
    <xs:sequence>
      <!-- le nom du club -->
      <xs:element name="nom" type="xs:string"/>
      <xs:element name="ville" type="xs:string"/>
      <xs:element name="scores" type="TypeScore"/>
    </xs:sequence>
    <!-- identifiant de club : souvent acronyme -->
    <xs:attribute name="id" type="xs:ID"/>
  </xs:complexType>
  
  <!-- l'élément clubs contient une séquence d'élément club -->
  <xs:element name="clubs">
    <xs:complexType>
      <xs:sequence>
       <xs:element name="club" type="TypeClub" minOccurs="0" maxOccurs="unbounded" />
     </xs:sequence>
   </xs:complexType>
   <!-- l'attribut id est une clef pour les clubs -->
   <xs:key name="clefClub">
     <xs:selector xpath="club"/>
     <xs:field xpath="@id"/>
   </xs:key>
  </xs:element>
  
</xs:schema>

=== jecisc/M1SGBD/TPXQuery2/foot_tp/clubs_j0.xml
<?xml version="1.0" encoding="utf-8"?>
<clubs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns="http://caronc/schema/foot"
             xsi:schemaLocation="http://caronc/schema/foot
                         http://www.fil.univ-lille1.fr/~caronc/SGBD/foot/clubs_scores.xsd">
    <club id="OL">
      <nom>Olympique Lyonnais</nom>
      <ville>Lyon</ville>
      <scores nb_journees = '0'>
        <nb_buts_marques>0</nb_buts_marques>
        <nb_buts_encaisses>0</nb_buts_encaisses>
        <nb_points>0</nb_points>
        <classement>0</classement>
      </scores>
    </club>
    <club id="LOSC">
      <nom>Lille Olympique Sporting Club</nom>
      <ville>Lille</ville>
      <scores nb_journees = '0'>
        <nb_buts_marques>0</nb_buts_marques>
        <nb_buts_encaisses>0</nb_buts_encaisses>
        <nb_points>0</nb_points>
        <classement>0</classement>
      </scores>
    </club>
    <club id="Bdx">
      <nom>Football club des Girondins de Bordeaux</nom>
      <ville>Bordeaux</ville>
      <scores nb_journees = '0'>
        <nb_buts_marques>0</nb_buts_marques>
        <nb_buts_encaisses>0</nb_buts_encaisses>
        <nb_points>0</nb_points>
        <classement>0</classement>
      </scores>
    </club>
    <club id="OM">
      <nom>Olympique Marseillais</nom>
      <ville>Marseille</ville>
      <scores nb_journees = '0'>
        <nb_buts_marques>0</nb_buts_marques>
        <nb_buts_encaisses>0</nb_buts_encaisses>
        <nb_points>0</nb_points>
        <classement>0</classement>
      </scores>
    </club>
    <club id="ACA">
      <nom>Athletic Club Ajaccien</nom>
      <ville>Ajaccio</ville>
      <scores nb_journees = '0'>
        <nb_buts_marques>0</nb_buts_marques>
        <nb_buts_encaisses>0</nb_buts_encaisses>
        <nb_points>0</nb_points>
        <classement>0</classement>
      </scores>
    </club>
    <club id="ESTAC">
      <nom>Espérance Sportive Troyes Aube Champagne</nom>
      <ville>Troyes</ville>
      <scores nb_journees = '0'>
        <nb_buts_marques>0</nb_buts_marques>
        <nb_buts_encaisses>0</nb_buts_encaisses>
        <nb_points>0</nb_points>
        <classement>0</classement>
      </scores>
    </club>
    <club id="ASNL">
      <nom>Association Sportive de Nancy-Lorraine</nom>
      <ville>Nancy</ville>
      <scores nb_journees = '0'>
        <nb_buts_marques>0</nb_buts_marques>
        <nb_buts_encaisses>0</nb_buts_encaisses>
        <nb_points>0</nb_points>
        <classement>0</classement>
      </scores>
    </club>
    <club id="Bas">
      <nom>Sporting Club de Bastia</nom>
      <ville>Bastia</ville>
      <scores nb_journees = '0'>
        <nb_buts_marques>0</nb_buts_marques>
        <nb_buts_encaisses>0</nb_buts_encaisses>
        <nb_points>0</nb_points>
        <classement>0</classement>
      </scores>
    </club>
    <club id="Lor">
      <nom>Football Club Lorient-Bretagne Sud</nom>
      <ville>Lorient</ville>
      <scores nb_journees = '0'>
        <nb_buts_marques>0</nb_buts_marques>
        <nb_buts_encaisses>0</nb_buts_encaisses>
        <nb_points>0</nb_points>
        <classement>0</classement>
      </scores>
    </club>
    <club id="Ren">
      <nom>Stade Rennais Football Club</nom>
      <ville>Rennes</ville>
      <scores nb_journees = '0'>
        <nb_buts_marques>0</nb_buts_marques>
        <nb_buts_encaisses>0</nb_buts_encaisses>
        <nb_points>0</nb_points>
        <classement>0</classement>
      </scores>
    </club>
    <club id="Tou">
      <nom>Toulouse Football Club</nom>
      <ville>Toulouse</ville>
      <scores nb_journees = '0'>
        <nb_buts_marques>0</nb_buts_marques>
        <nb_buts_encaisses>0</nb_buts_encaisses>
        <nb_points>0</nb_points>
        <classement>0</classement>
      </scores>
    </club>
    <club id="ASSE">
      <nom>Association Sportive de Saint Etienne</nom>
      <ville>Saint Etienne</ville>
      <scores nb_journees = '0'>
        <nb_buts_marques>0</nb_buts_marques>
        <nb_buts_encaisses>0</nb_buts_encaisses>
        <nb_points>0</nb_points>
        <classement>0</classement>
      </scores>
    </club>
    <club id="VA">
      <nom>Valenciennes Football Club</nom>
      <ville>Valenciennes</ville>
      <scores nb_journees = '0'>
        <nb_buts_marques>0</nb_buts_marques>
        <nb_buts_encaisses>0</nb_buts_encaisses>
        <nb_points>0</nb_points>
        <classement>0</classement>
      </scores>
    </club>
    <club id="Soc">
      <nom>Football Club de Sochaux-Montbéliard</nom>
      <ville>Sochaux</ville>
      <scores nb_journees = '0'>
        <nb_buts_marques>0</nb_buts_marques>
        <nb_buts_encaisses>0</nb_buts_encaisses>
        <nb_points>0</nb_points>
        <classement>0</classement>
      </scores>
    </club>
    <club id="PSG">
      <nom>Paris Saint Germain</nom>
      <ville>Paris</ville>
      <scores nb_journees = '0'>
        <nb_buts_marques>0</nb_buts_marques>
        <nb_buts_encaisses>0</nb_buts_encaisses>
        <nb_points>0</nb_points>
        <classement>0</classement>
      </scores>
    </club>
    <club id="Mon">
      <nom>Montpellier-Herault Sports Club</nom>
      <ville>Montpellier</ville>
      <scores nb_journees = '0'>
        <nb_buts_marques>0</nb_buts_marques>
        <nb_buts_encaisses>0</nb_buts_encaisses>
        <nb_points>0</nb_points>
        <classement>0</classement>
      </scores>
    </club>
    <club id="ETG">
      <nom>Evian Thonon Gaillard Football Club</nom>
      <ville>Evian</ville>
      <scores nb_journees = '0'>
        <nb_buts_marques>0</nb_buts_marques>
        <nb_buts_encaisses>0</nb_buts_encaisses>
        <nb_points>0</nb_points>
        <classement>0</classement>
      </scores>
    </club>
    <club id="OGCN">
      <nom>Olympique Gymnaste Club de Nice Côte d'Azur</nom>
      <ville>Nice</ville>
      <scores nb_journees = '0'>
        <nb_buts_marques>0</nb_buts_marques>
        <nb_buts_encaisses>0</nb_buts_encaisses>
        <nb_points>0</nb_points>
        <classement>0</classement>
      </scores>
    </club>
    <club id="SB">
      <nom>Stade Brestois</nom>
      <ville>Brest</ville>
      <scores nb_journees = '0'>
        <nb_buts_marques>0</nb_buts_marques>
        <nb_buts_encaisses>0</nb_buts_encaisses>
        <nb_points>0</nb_points>
        <classement>0</classement>
      </scores>
    </club>
    <club id="Rei">
      <nom>Stade de Reims</nom>
      <ville>Reims</ville>
      <scores nb_journees = '0'>
        <nb_buts_marques>0</nb_buts_marques>
        <nb_buts_encaisses>0</nb_buts_encaisses>
        <nb_points>0</nb_points>
        <classement>0</classement>
      </scores>
    </club>
</clubs>
